/// <reference types="vitest/config" />
import { createHash } from 'node:crypto';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { defineConfig, type Plugin } from 'vite';

/**
 * Content Security Policy for the static build. GitHub Pages can't send
 * headers, so it goes in a <meta> tag. Dev mode injects styles with JS, so
 * the tag is added to builds only.
 *
 * connect-src also allows https: and http://localhost so the app can read a
 * relay's `GET /` info endpoint (see docs/decisions.md).
 */
const CSP = [
  "default-src 'self'",
  "script-src 'self' 'wasm-unsafe-eval'",
  "worker-src 'self' blob:",
  "connect-src 'self' wss: https: ws://localhost:* ws://127.0.0.1:* http://localhost:* http://127.0.0.1:*",
  "style-src 'self'",
  "img-src 'self' data:",
  "font-src 'self'",
  "base-uri 'none'",
  "form-action 'none'",
].join('; ');

function csp(): Plugin {
  return {
    name: 'spool-csp',
    apply: 'build',
    transformIndexHtml(html) {
      return html.replace(
        '<meta charset="utf-8" />',
        `<meta charset="utf-8" />\n    <meta http-equiv="Content-Security-Policy" content="${CSP}" />`,
      );
    },
  };
}

/**
 * Writes a hand-rolled service worker that precaches the app shell (HTML, JS,
 * CSS, fonts, icons) and caches other same-origin assets (the WASM engine,
 * libarchive) on first use. index.html is network-first.
 */
function serviceWorker(): Plugin {
  return {
    name: 'spool-sw',
    apply: 'build',
    generateBundle(_opts, bundle) {
      const shell = Object.keys(bundle).filter(
        (f) => /\.(js|css|woff2|svg|png|webmanifest)$/.test(f) && !/archive|libarchive/.test(f),
      );
      const statics = ['icon.svg', 'icon-192.png', 'icon-512.png', 'icon-maskable-512.png', 'manifest.webmanifest', 'fonts/Geist-Variable.woff2', 'fonts/GeistMono-Variable.woff2'];
      const assets = ['./', ...new Set([...shell, ...statics])].map((f) => (f === './' ? f : `./${f}`));
      const version = createHash('sha256').update(assets.join('\n')).digest('hex').slice(0, 12);
      const source = `// Generated by vite.config.ts. Precaches the app shell.
const CACHE = 'spool-${version}';
const SHELL = ${JSON.stringify(assets)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('spool-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (req.mode === 'navigate' || url.pathname.endsWith('/index.html')) {
    // Network first, so a new release shows up on the next visit.
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put('./', copy));
          return res;
        })
        .catch(() => caches.match('./').then((r) => r || Response.error())),
    );
    return;
  }
  // Hashed assets never change: cache first.
  e.respondWith(
    caches.match(req).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res.ok && /\\/assets\\//.test(url.pathname)) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        }),
    ),
  );
});
`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source });
    },
  };
}

export default defineConfig({
  base: './',
  plugins: [svelte(), csp(), serviceWorker()],
  worker: {
    format: 'es',
  },
  build: {
    target: 'es2022',
    sourcemap: false,
    assetsInlineLimit: 0,
    reportCompressedSize: true,
  },
  server: {
    fs: { allow: ['..', '../..'] },
  },
  test: {
    include: ['src/**/*.test.ts'],
    environment: 'node',
  },
});
